### ISSUE TITLE
Implement OpenGraph meta tags to improve link previews

### ISSUE THREAD

**Issue by BelfordZ** [MetaMask/metamask-docs#814] opened 2023-06-16 19:19 UTC
See https://ogp.me/ for more details.

Links shared in various places should have a nice look to them. Heres an example of what it currently looks like when you link the docs on twitter:

![image](https://github.com/MetaMask/metamask-docs/assets/1787231/d162c099-6d38-470f-a30e-893e3d7cbf92)

- using docusarus global https://docusaurus.io/docs/seo#global-metadata would be a good start
- using same meta tags as metamask.io would be a good start as well.

**Comment by alexandratran** [comment] 2024-01-10 23:57
duplicate of #800

**Closed by alexandratran** 2024-01-10 23:57 UTC
Labels: platform, team-devex
