### ISSUE TITLE
Detect if the metamask is installed fail

### ISSUE THREAD

**Issue by goplaygo** [MetaMask/metamask-docs#232] opened 2021-03-12 11:02 UTC
Hi,
I use the Metamask "Quick Started" sample code to detect that,
But I always got the alert 'ethereum is not defined.' even the metamask is installed.

The Metamask info is V9.1.1 in Chrome.
Someone help me to fix that?
thank you :)

```  html
<button class ="walletbtn" >Connect Wallet</button>
```
``` javascript
        const ethereumButton = document.querySelector('.walletbtn');
        ethereumButton.addEventListener('click', () => {
        //Will Start the metamask extension
        ethereum.request({ method: 'eth_requestAccounts' });
        });
```
And chrome back 
```
ethereum is not defined
```

**Comment by BboyAkers** [comment] 2021-03-12 23:06
Thanks for the info! I'll check it out this weekend and see what's wrong! 🙂

**Comment by BboyAkers** [comment] 2021-04-23 02:40
Have you tried typing `ethereum` in your console? Also, try re-installing Metamask, that may work!

**Comment by BboyAkers** [comment] 2021-05-01 19:09
Closing. Tested this version and couldn't reproduce in Chrome, Edge, or Firefox.

**Closed by BboyAkers** 2021-05-01 19:09 UTC
