### ISSUE TITLE
Irregularity in the `URL text` design

### ISSUE THREAD

**Issue by subhamkumarr** [MetaMask/metamask-docs#1105] opened 2024-01-25 16:39 UTC
## Description:
There is an irregularity in the URL text design. 
## Error:
The URL text is underlined at all times, contrary to the established design. According to the design guidelines, the URL text should only be underlined when the user hovers over it. Additionally, the URL text should appear in blue.

 ## Irregularity in design screenshot:
![Screenshot (1045)](https://github.com/MetaMask/metamask-docs/assets/99977240/eb5b8dbb-f412-4ae5-806d-3705ad4fcb14)

## Everywhere URL text design:
https://www.loom.com/share/eeed5da089ef42678adb8c7f4e2512ac?sid=8ec55ea6-551a-4837-8c6a-a968a6734ecf

**Comment by subhamkumarr** [comment] 2024-01-25 16:42
@alexandratran, may I work on this issue, ma'am?

**Comment by alexandratran** [comment] 2024-01-25 18:28
@subhamkumarr This is the expected behavior, since this is the default style of links for [Docusaurus admonitions](https://docusaurus.io/docs/3.0.1/markdown-features/admonitions). However, you're welcome to modify the style to make it match the links in the regular text! Assigned to you.

**Closed** 2024-09-26 23:59 UTC
Labels: platform
